Add scripts for dataset download and augmentation
chipGPT/nanoGPT pull request #16
Opened 2023-10-20 01:41 UTC by gkielian

These allow replication of tinystories augmentation (in this case translation) into other languages.

These also unblock the possibility of augmenting with the summaries pre-provided it turns out in the json formatted stories (these actually are only in the json and not in the text stories which is a fortuitous find).

2023-11-01 07:21 UTC, klei22 requested changes
After trying, there are two changes needed.

2023-11-01 07:21 UTC, klei22 commented on data_augmentation/tinystories_en.sh
> +      ./venv/bin/python3 aug_translation.py -i ${input} -o ${output} -j -l ${lang}&
Change to `python3`

2023-11-01 07:21 UTC, klei22 commented on data_augmentation/tinystories_en.sh
> +    input="./datasets/json_stories/data${i}.json"
Add 'archive' after json_stories

2023-11-01 21:09 UTC, gkielian commented on data_augmentation/tinystories_en.sh
> +      ./venv/bin/python3 aug_translation.py -i ${input} -o ${output} -j -l ${lang}&
Good catch! I changed this back to python3 (was switching between pip vs conda setups and forgot to remove the hotfix).

2023-11-01 21:11 UTC, gkielian commented on data_augmentation/tinystories_en.sh
> +      ./venv/bin/python3 aug_translation.py -i ${input} -o ${output} -j -l ${lang}&
Sharing direct link to diff showing resolution: https://github.com/chipGPT/nanoGPT/pull/16/commits/d111aa50710799c3f20455ecc5c6b6e4e80400f8

2023-11-01 21:11 UTC, gkielian commented on data_augmentation/tinystories_en.sh
> +    input="./datasets/json_stories/data${i}.json"
Sharing direct link to diff showing resolution: https://github.com/chipGPT/nanoGPT/pull/16/commits/d111aa50710799c3f20455ecc5c6b6e4e80400f8

2023-11-02 05:55 UTC, klei22 approved these changes

2023-11-02 05:56 UTC, klei22 commented
Changes look good.

2023-11-02 05:56 UTC, merged