Contributing additional Softmax Variants and refactored config to switch smoothly between them.
chipGPT/nanoGPT pull request #19
Opened 2023-10-24 03:27 UTC by gkielian

Added SigSoftmax (as nn.Module): https://arxiv.org/abs/1805.10829
Added a base 2 variation of SigSoftmax (as nn.Module)
Refactored Softermax into a nn.Module 

With each softmax variation inheriting from nn.Module, refactored to leverage polymorphism to simplify the selection of softmax variation.

Now simply use text setting within the Config, e.g. `softmax_variant = "softermax"` to choose or test out the softmax variation type.

2023-11-01 07:24 UTC, klei22 requested changes
Probably should rebase, or at least remove changes to train.py

2023-11-01 07:24 UTC, klei22 commented on train.py
Train.py should not have changed.

2023-11-01 21:13 UTC, gkielian commented on train.py
Just did a rebase and updated in order to make sure train.py is up to date with main branch.

Looks like things are now good :+1:

2023-11-02 05:19 UTC, klei22 commented
Works except will need to remove the configurator,py mention in the sample.py script.

Should mention, noticed some `nans` when trying to train with SigSoftmax and the "Softermax" without xmax as False. 
We should keep a note of this somewhere.

2023-11-02 05:54 UTC, klei22 commented
Changes look good.

2023-11-02 05:54 UTC, klei22 approved these changes

2023-11-02 05:55 UTC, merged